<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Implementation\" />
    <Folder Include="Implementation\Section_0\" />
    <Folder Include="Implementation\Section_1\" />
  </ItemGroup>

</Project>
